on:
  push:
    tags:
    - '*'
permissions :
    contents : write

name: Build and Release 

jobs:
  build-linux-x64:
    runs-on : ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 3.38.5
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux

      - name: Archive Linux Build
        run : tar -czf pense-linux-x64.tar.gz -C build/linux/x64/release/bundle .
      - uses: actions/upload-artifact@v4
        with:
          name: pense-linux-x64
          path: pense-linux-x64.tar.gz

  build-linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 3.38.5
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux

      - name: Archive Linux Build
        run : tar -czf pense-linux-arm64.tar.gz -C build/linux/arm64/release/bundle .
      - uses: actions/upload-artifact@v4
        with:
          name: pense-linux-arm64
          path: pense-linux-arm64.tar.gz
    #   build-linux:
    #     strategy:
    #         matrix:
    #             os : [ubuntu-latest,ubuntu-24.04-arm]

    #     runs-on: $ {{matrix.os}}
    #     env :
    #         Arch : ${{matrix.os == 'ubuntu-latest' && 'x64' || 'arm64' }} 
    #     steps:
    #       - name: Clone repository
    #         uses: actions/checkout@v4
    #       - name: Set up Flutter
    #         uses: subosito/flutter-action@v2
    #         with:
    #           channel: master
    #           flutter-version: 3.38.5
    #       - run: |
    #           sudo apt-get update -y
    #           sudo apt-get install -y ninja-build libgtk-3-dev
    #       - run: flutter build linux

    #       - name: Archive Linux Build
    #         run : tar -czf build-${{matrix.os}}.tar.gz -C build/linux/$Arch/release/bundle .
    #       - uses: actions/upload-artifact@v4
    #         with:
    #           name: pense-${{matrix.os}}
    #           path: build-${{matrix.os}}.tar.gz
  build-windows-x64:
    strategy:
        fail-fast: false
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 3.38.5
      - run: flutter build windows
      - name: Archive Windows Build
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath pense-windows-x64.zip

      - uses: actions/upload-artifact@v4
        with:
          name: pense-windows-x64
          path: pense-windows-x64.zip


    #   build-windows-arm64:
    #     strategy:
    #         fail-fast: false
    #     runs-on: windows-11-arm
    #     steps:
    #       - name: Clone repository
    #         uses: actions/checkout@v4
    #       - name: Set up Flutter
    #         uses: subosito/flutter-action@v2
    #         with:
    #           channel: master
    #           flutter-version: 3.38.1
    #       - run: flutter build windows
    #       - name: Archive Windows Build
    #         run: Compress-Archive -Path build\windows\arm64\runner\Release\* -DestinationPath pense-windows-arm64.zip

    #       - uses: actions/upload-artifact@v4
    #         with:
    #           name: pense-windows-arm64
    #           path: pense-windows-arm64.zip


    #   build-windows:
    #     strategy:
    #         fail-fast: false
    #         matrix:
    #             os : [windows-latest,windows-11-arm]
    #     runs-on: ${{matrix.os}}
    #     env:
    #         Arch : ${{matrix.os == 'windows-latest' && 'x64' || 'arm64' }} 
    #     steps:
    #       - name: Clone repository
    #         uses: actions/checkout@v4
    #       - name: Set up Flutter
    #         uses: subosito/flutter-action@v2
    #         with:
    #           channel: master
    #           flutter-version: 3.38.5
    #       - run: flutter build windows
    #       - name: Archive Windows Build
    #         run: Compress-Archive -Path build\windows\$Arch\runner\Release\* -DestinationPath build-${{matrix.os}}.zip

    #       - uses: actions/upload-artifact@v4
    #         with:
    #           name: pense-${{matrix.os}}
    #           path: ${{matrix.os}}.zip
 
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build apk
      - name: Rename apk
        run: mv build/app/outputs/flutter-apk/app-release.apk pense.apk

      - uses: actions/upload-artifact@v4
        with:
          name: pense-android
          path: pense.apk
      - run: flutter build appbundle
      - name: Rename aab
        run: mv build/app/outputs/bundle/release/app-release.aab pense.aab
      - uses: actions/upload-artifact@v4
        with:
          name: pense-android-bundle
          path: pense.aab
  publish:
    needs:
      - build-linux-x64
      - build-windows-x64
      - build-linux-arm64
      - build-android
    runs-on: ubuntu-latest
    steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            path: artifacts
        - name: Create release
          uses : softprops/action-gh-release@v2
          with:
            tag_name: ${{ github.ref_name }}
            name: Release ${{ github.ref_name }}
            files:  |
             artifacts/pense-linux-x64/pense-linux-x64.tar.gz
             artifacts/pense-windows-x64/pense-windows-x64.zip
             artifacts/pense-linux-arm64/pense-linux-arm64.tar.gz
             artifacts/pense-android/pense.apk
             artifacts/pense-android-bundle/pense.aab
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}